# Defaults for local `helm template`; Terraform overrides all of these.

argocdNamespace: argocd

repositories:
  - name: django-app
    url: https://github.com/dfinchenko/my-microservice-project.git
    type: git

applications:
  - name: django-app
    project: default
    repoURL: https://github.com/dfinchenko/my-microservice-project.git
    targetRevision: final-project
    path: charts/django-app
    destinationServer: https://kubernetes.default.svc
    destinationNamespace: django
    autoSync: true
