global:
  domain: ""

configs:
  params:
    # TLS terminates at the load balancer.
    server.insecure: true

server:
  service:
    type: ${server_service_type}

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

applicationSet:
  enabled: false

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

dex:
  enabled: false

notifications:
  enabled: false
